name: fksarajevo_shop
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_flavorizr: ^2.4.1

flutter:
  uses-material-design: true

  # Mora biti uvučeno TAČNO 2 razmaka od ivice
  assets:
    # Mora biti uvučeno TAČNO 4 razmaka od ivice
    - assets/images/fksarajevo.png

flavorizr:
  flavors:
    dev:
      app:
        name: "FKS Shop Dev"
      android:
        applicationId: "com.example.fksarajevoshop.dev"
      ios:
        bundleId: "com.example.fksarajevoshop.dev"
    prod:
      app:
        name: "FKS Shop"
      android:
        applicationId: "com.example.fksarajevoshop"
      ios:
        bundleId: "com.example.fksarajevoshop"