name: fksarajevo_shop
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  google_sign_in: ^6.2.2
  flutter_bloc: ^9.0.0
  get_it: ^8.0.3
  go_router: ^14.8.0
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_flavorizr: ^2.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/fksarajevo.png

flavorizr:
  flavors:
    dev:
      app:
        name: "FKS Shop Dev"
      android:
        applicationId: "com.example.fksarajevoshop.dev"
      ios:
        bundleId: "com.example.fksarajevoshop.dev"
    prod:
      app:
        name: "FKS Shop"
      android:
        applicationId: "com.example.fksarajevoshop"
      ios:
        bundleId: "com.example.fksarajevoshop"
